### ISSUE TITLE
Not working with non-ascii character 

### ISSUE THREAD

**Issue by ShinyChang** [dollarshaveclub/shave#10]
Non-ascii (e.g. Chinese) may have no space between words. 

![image](https://cloud.githubusercontent.com/assets/1590707/19830368/f6889bd6-9e28-11e6-8248-55050a92e77f.png)

**Comment by yowainwright** [comment]
@ShinyChang this is a great observation! I'd like to support this _new_ feature - making shave work for non-spaced languages. 🙌

Initially, because adding this feature would change the way shave is written, I will discuss it with my team on Monday. @briangonzalez @jakiestfu @pwfisher 

My initial thought would be to write another version of the plugin (within the same `src/` & compiled `dist/`) that would support non-spaced scenarios.

**Comment by briangonzalez** [comment]
@yowainwright 

Check out PR #12 – simple support for non whitespace delimited languages. Let me know what you think.

If you like this direction, I'll come back with some tests and an updated README.

**Comment by yowainwright** [comment]
@briangonzalez I wrote a test. Can we rendezvous on this later tonight/tomorrow? 📍

**Comment by yowainwright** [comment]
@ShinyChang we've added support for non-spaced languages. It's working well in all ways we've thought to test. 

Thank you so much for pointing out this opportunity to improve our product. 🙌

**Comment by ShinyChang** [comment]
Thanks, good job!
