### ISSUE TITLE
Add an API to apply truncated text to target container

### ISSUE THREAD

**Issue by adrian-marcelo-gallardo** [dollarshaveclub/shave#153]
## What Is the issue?
**Feature request:** provide an additional API/method for truncating text before assigning to container.

`shave` looks for elements marked to be truncated and then applies it; so, there is a small blink happening because on first render the element displays full text.

For integrating with modern frameworks like React or Vue, would be more convenient to have a programatic API to assign the text to a target element.

## Provide issue context below using code examples, images, or links

I would like to use the library this way:

```
import shave from 'shave'

const text = 'Very long text that will be truncated...'
const container = document.querySelector('#text-wrapper')
const maxHeight = container.offsetHeight // This could be calculated by the library if not provided

shave.fillContainer(container, text, maxHeight)
```

----

> Read about references issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Provide paragraph text responses to each header.

**Comment by dwatkinsweb** [comment]
I agree allowing it to auto-calculate the height based on the element somehow. I have a bunch of elements with varying max-height set in css that is just getting cut off using overflow:hidden, but I would like to be able to use this to add the ellipses. Right now, I'm guessing I would have to do each one individually myself instead of letting the library figure it out.

**Comment by juanmardefago** [comment]
@dwatkinsweb I kinda implemented something like that in a fork, since my personal use case was to just truncate any text that overflows the container it's in, and to make it simpler to use, it would've been nice to have the library calculate how big the container is.

To make it simpler to use, I added a percentage height parser, so that you could just say:
`element.shave('100%');`
and it would cut any text that overflows the 100% height of the container.

It would also be possible to use any other percentage, and supposedly it would work, the thing is that those changes kinda made us debate about whether that was needed, or if it's just a tradeoff between simplicity and ease of use. Also adding that lead to some execution paths that might be bug-prone.

Anyhow, here's the PR for that functionality, in case you want to see how that worked.
https://github.com/dollarshaveclub/shave/pull/155

**Comment by yowainwright** [comment]
Closing per @juanmardefago's thoughtful comment.
