### ISSUE TITLE
destructuring & parameters

### ISSUE THREAD

**Issue by cedriceberhardt** [dollarshaveclub/shave#20]
HI. Just an input about code simplification.

As you are using ES6, you could define your function like:
```
export default function shave(target, maxHeight, { character = '…', classname = 'js-shave', spaces = true } = {})
```
instead of all the default object soup.

**Comment by yowainwright** [comment]
Thanks for your feedback! 💪

The 'default object soup' is done the way it is because when compiled like the comment above suggests it becomes es6 compilation soup aka: code is added by the compiler to make the the plugin work currently (larger file size, less clear). 

Shave's goal from a code quality perspective is to enhance code legibility optimally. This means it uses es6 as a tool rather than a crutch. If shave gets suggestions that enhance speed (majorly) or clarity in both before compile & after - we'all add it! 🚜

**Comment by jakiestfu** [comment]
To be fair, the source code is what people will modify. The distribution files are an artifact,  and their complexity shouldn't matter.  ES6 provides this feature for us natively, and not leveraging it in favor of other ways is not looking to the future, in my opinion

**Comment by yowainwright** [comment]
Thanks for the feedback. 

Artifacts are what is used in production so I disagree with that comment and it actually concerns me. 

We implemented the suggested approach in this thread before shave was open sourced based on a suggestion 😉 - the resulting 'artifact' was not optimal aka there where functions and variables added making the file size larger and the code less legible.

**Comment by yowainwright** [comment]
Here's a an example of what can happen when compilers are used without awareness of the result. https://github.com/dollarshaveclub/shave/commit/f9bf09f1d38d52f4ec0e3e19a37c855a96aeee1e

**Comment by jakiestfu** [comment]
That's an example for something that is definitely not something I would use due to the nature of the transpired code, but default parameter values add a negligible file size, especially considering that the source already does something similar.

That being said, why use ES6 at all in these cases if larger file size after transpiration is a concern?

**Comment by yowainwright** [comment]
ES6 is awesome! It's used thoughtfully in Shave - along with some tried and true things - like the for loop which has also been heavily critiqued. I personally don't care if a new race car engine looks faster if it's not. Now if it was the car ... 😎

**Comment by yowainwright** [comment]
@cedriceberhardt Thanks again by the way. We very much appreciate the notes! 🍻 

The back and forth was among my teammate and I - we'd discussed your suggestion previously. 😊

**Comment by cedriceberhardt** [comment]
You are welcome. I understand your point of view and it is good info to keep in mind.
