### ISSUE TITLE
Better support for resizing

### ISSUE THREAD

**Issue by slafleche** [dollarshaveclub/shave#56]
The [example](https://codepen.io/yowainwright/pen/yVBxGY) given on code pen works ok when you have one element to resize, but doesn't scale to having multiple elements very easily. 

There's function to "reset" the element back to how it was and there's no option to pass an object instead of a selector to the element. This makes it difficult to optimize truncating multiple elements on window resize. If we need to go through each element, reset them manually and then search for all those elements a second time, it's a lot slower than being able to pass the element directly. 

Why not make `shaveEl` public?

**Comment by yowainwright** [comment]
@slafleche, I briefly read your note. I will re-read your note soon and respond/update. 🙏

**Comment by yowainwright** [comment]
@slafleche I'm not convinced the shave plugin should support resizing beyond the note in the readme. 

The reason I'm thinking this way is that customers don't usually resize the thing their viewing _shaved_ text on. 

----
**For consideration**

If I had to implement a cleanup method so that the shave plugin could be invoked and then be removed (cleaned-up), I would do that outside of the plugin so that the plugin could/can maintain it's minimal byte size and focus. 

If you'd like to PR or submit a strong use-case for `resize` &/or _clean-up_ support, I'm definitely ready to learn about what I might be not understanding. ~Thank you! 🙌

**Comment by slafleche** [comment]
It's true that customers don't usually resize their window. However, if they switch from portrait to landscape, they are, technically, resizing their window.

Can you make `shaveEl` public at least? That wouldn't make the file size bigger and would allow to easily fix these issues outside of the plugin. It's unfortunate to query the DOM once to undo the shave and then redo it.

**Comment by yowainwright** [comment]
@slafleche thanks for your considerations! I am making `shave` more simple in its structure. It will just be a function shortly.

**Comment by slafleche** [comment]
🙌 Thanks!

**Comment by yowainwright** [comment]
Okay, @slafleche I simplified shave—the _shave_ function now takes in no other functions (no more `shaveEl`).  Hope that resolves your use case!!! 🙏
