### ISSUE TITLE
Simple solution for toggling?

### ISSUE THREAD

**Issue by sashtown** [dollarshaveclub/shave#84]
Is there a simple way to toggle the shave (like some kind of "unshave") with a class or something? I simply want the text to be "shaved" on page load and then "unshaved" by clicking on the whole text (or some button). I'm using jQuery. Thx in advance!

**Comment by yowainwright** [comment]
Hey @sashtown! Thanks for reaching out. 

This issue (a feature like "unshave") has been discussed previously. It is in past issues, I think. 🤔

If I remember correctly, this feature was not added to maintain the size of this tiny utility. Instead, tooling is there so that the implementer can do it as they need. I think there are a few demos in the [notes section](https://github.com/dollarshaveclub/shave#notes) of the README.md. 

Let me know if that helps! If you feel there is a need for a README.md update or would like to purpose a API update, please submit a pull request. 

~Thanks again!!!

**Comment by sashtown** [comment]
Hey @yowainwright, thanks for your reply! Great to see some people on Github reacting that fast. 💪 

Yeah, I checked the demo but I guess that's not what I've been searching for. And since I'm not a JS pro I think I'll rather go with some progressive enhancement in terms of `line-clamp` with CSS.

**Comment by yowainwright** [comment]
@sashtown if the webpage that is being worked on does not need to support older browsers and the implementer has the ability to discuss how text truncation will look/work in Internet Explorer with the team outside of engineering—that is the decision I would recommend!
